- src/db/sql/config/config_definitions.sql
- src/metrics/db_stats/11/metric.sql
- src/metrics/db_stats/11/metric_su.sql
- src/metrics/db_stats/12/metric.sql
- src/metrics/db_stats/12/metric_su.sql
- src/metrics/db_stats/14/metric.sql
- src/metrics/db_stats/14/metric_su.sql
- src/metrics/db_stats/15/metric.sql
- src/metrics/db_stats/15/metric_su.sql
- src/metrics/invalid_indexes/11/metric.sql
- src/metrics/unused_indexes/11/metric.sql
import from cybertec-postgresql/pgwatch2#691
> [+] add new metrics for invalid and unused indexes

- src/config/cmdoptions.go
- src/database.go
- src/db/conn.go
- src/log/formatter.go
- src/main.go
- src/sinks/json_file.go
- src/sinks/multiwriter.go
- src/sinks/postgres.go
- src/sinks/prometheus.go
- src/sources/postgres.go
- src/sources/yaml.go
* split Metrics into Metrics & Measurements
* move options to appropriate groups
* deprecate `UseConnPooling` option
* improve Postgres writer log entries
> [!] add `Measurements` group and use URIs for `--sink` options

- src/log/log_broker_hook.go
- src/log/log_broker_hook_test.go
Close #387
by doing it backward it should be fine
> [-] fix possible index out of bound issue, fixes #387

- src/webui/.eslintignore
- src/webui/src/layout/Logs/LogGrid/logOutput.tsx
- src/webui/tsconfig.json
This pull request addresses two issues identified during code review and linting:
1. **Removal of Deprecated Dependency suppressImplicitAnyIndexErrors from tsconfig.json**:
Removed the deprecated dependency suppressImplicitAnyIndexErrors from the tsconfig.json file to ensure compatibility with the latest TypeScript versions and maintain codebase cleanliness.
2. **Exclude .eslintrc.js from ESLint**:
.eslintrc has been added to .eslintignore file, to avoid error squiggles
> [-] fix deprecated dependencies on WebUI 

- src/webserver/cors.go
- src/webserver/webserver.go
thanks @whitetown for pointing this out
> [+] allow CORS from `http://localhost:4000` for webui debugging

- src/metrics/metrics.yaml
cherry picked from cybertec-postgresql/pgwatch2#778
> [+] add `usename` to `replication` metric

- src/metrics/metrics.yaml
cherry picked from cybertec-postgresql/pgwatch2#783
> [-] fix FREEZE age for partitioned tables in `table_stats`

- src/reaper/reaper.go
- src/sources/patroni.go
- src/sources/types.go
- src/sources/types_test.go
[+] add `MonitoredDatabase.Clone()`
[*] remove `MonitoredDatabase.DBUniqueNameOrig`, use `ConnStr` instead
> [-] fix `MonitoredDatabase.ResolveDatabasesFromPostgres()`, fixes #467

- .github/workflows/build.yml
- src/db/bootstrap_test.go
[*] remove Postgres instance init section
[+] enable Ubuntu and Windows jobs
[+] add trigger on push to master branch
> [+] improve Build & Test GHA workflow

- src/metrics/metrics.yaml
based on cybertec-postgresql/pgwatch2#804
> [!] add support for PostgreSQL v17

- docker-compose.yml
- docker/Dockerfile
- docker/Dockerfile.postgres-plpython3u
custom image allows to install plpython3u and provides smooth experience
for cpu_load metric which is enabled by default.
> [+] use custom Postgres image for compose

- internal/sources/doc.go
> [-] fix minor typo

- docker/bootstrap/prometheus.yml
- docker/compose.grafana.yml
- docker/compose.pgwatch.yml
- docker/compose.prometheus.yml
- grafana/dashboards.yml
- grafana/prometheus/v11/1-global-db-overview.json
- grafana/prometheus/v11/db-overview.json
- grafana/prometheus/v11/health-check.json
- grafana/prometheus/v11/table-details.json
- grafana/prometheus/v11/tables-top.json
- grafana/prometheus_datasource.yml
Somethings seems has changed in how Grafana handles things, some panels failed to load. Adjusted on latest Grafana v11.4.0
> [*] Prometheus Grafana v11 dashboard updates

- docker/compose.pgbouncer.yml
- docker/compose.pgpool.yml
- docker/compose.postgres.yml
- docker/compose.timescaledb.yml
- docker/docker-compose.timescaledb.yml
- docker/docker-compose.yml
- extract pgbouncer into separate .yml
- rename `standby` service to `postgres-standby`
- add pgbouncer and pgpool to timescale based compose file
> [+] add pgpool service to docker compose files

- .github/workflows/build.yml
- go.mod
- go.sum
- internal/cmdopts/cmdmetric.go
- internal/reaper/database.go
- internal/reaper/file.go
- internal/reaper/metric.go
- internal/reaper/metric_test.go
- internal/reaper/psutil.go
- internal/reaper/psutil_test.go
- internal/reaper/reaper.go
- internal/sources/conn.go
- internal/sources/conn_test.go
- add `SourceConn.GetClusterIdentifier()`
- use `SourceConn` in `FetchStatsDirectlyFromOS()`
- remove `MetricFetchConfig`
> [*] replace `MetricFetchConfig` with `SourceConn` in `FetchMetrics()`

- docs/tutorial/custom_installation.md
And while at it, fix two typos.
> [*] use consistent password in install docs

- api/types.go
> [+] add `DeleteOp` and `AddOp` consts to `api`

- internal/reaper/reaper.go
- internal/reaper/reaper_test.go
- internal/sources/types.go
- internal/sources/types_test.go
This commit fixes #797 changes. 
Reported by @0xgouda
> [*] add "default" group processing

- internal/reaper/reaper.go
move the shutdown code to the first `monitoredSource.IsInRecovery && monitoredSource.OnlyIfMaster` check and remove the later check becuase it will always be false
closes: #812
> [*] fix `master only` postgres source shutdown due to catched `InRecovery` state logic

- grafana/postgres/v12/1-global-db-overview.json
- internal/metrics/metrics.yaml
- Import a new dashboard version from gitlab.com/postgres-ai/pgwatch2
- add datfrozenxid, postgres_role, archiver_pending_count metrics
> [+] improve "Global Database Overview" dashboard

- docs/howto/sizing_recommendations.md
> [*] add note in sizing docs about metrics returning thousands of rows
