src/config/cmdparser.go
src/config/config.go
src/log/log.go
src/log/log_broker_hook.go
src/main.go
src/sinks/postgres.go

Not every sink requires batching, e.g. Prometheus, plain files. From now writer implementation is responsible for batching of metric data.
`[*]` rename `BatchingDelayMs` to `BatchingDelay` and allow duration format 
`[*]` remove `MetricsBatcher()`
`[+]` implement batch writes in `sinks.PostgresWriter`

[!] move metric batching to sinks from the gatherer

---

src/database.go
src/logparse.go
src/main.go
src/metrics/io.go
src/metrics/types.go
src/sinks/json_file.go
src/sinks/multiwriter.go
src/sinks/postgres.go
src/sinks/prometheus.go

Everywhere in code where we are talking about defining what and how to monitor, we call it `Metric`. Everywhere in code where we are working with the real data obtained from sources, we call that `Measurement`.
For example, `"table_bloat"` is a **metric** showing how many bloated space a table occupies. And `"bloat_percent":2,"table_name":"foo", "epoch_ns":1705078795154269000,"real_dbname":"pgwatch3"` is a **measurement**.

[*] use `Metric` term for definition and `Measurement` for data gathered

---

build-docker-demo.sh
docker-compose.yml
docker/Dockerfile
docker/bootstrap/init_test_monitored_db.sh
docker/demo/Dockerfile

* bump versions
* use new ENVs, e.g. `PW3_SINK`
* fix docker bootstrap script

[+] bump Node to v21, Postgres to v16, Grafana to v10.3 in docker images

---

docker-compose.yml
docker/bootstrap/2_init_pgwatch_db.sh

In PR #371, deprecated helper files were removed, but their references were not removed from the docker-compose.yml file.

[*] remove references to deprecated metric files from docker-compose.yml

---

src/api.go

The backend was returning a JSON string containing the value 'NaN', which prevented the stats_summary page from loading. This erroneous response could not be properly parsed, thus preventing the frontend from retrieving values from the response data. Adjusted the backend response data to ensure valid JSON formatting.

[-] fix JSON format issue causing webpage loading failure

---

src/webserver/server_test.go

while I was trying to understand how the webserver worked I noticed that the tests had not yet been written, so I wanted to try to write some to better understand how the API works and to help those who come after me to understand how to use the api as the tests also partly act as documentation.
This pull request adds test cases for the webserver module. I've included test cases for the main routes to ensure they return the expected responses. These tests use the httptest package to mock HTTP requests.
Please review and let me know your feedback.
Changes Made:
- Added test cases for the webserver module
- Utilized httptest package to mock HTTP requests
- Ensured that the main routes return the expected responses
- Ensure that the jwt token works
Files Changed:
- …

[+] add test cases to webserver api

---

README.md

> [+] Running 2/0
>  ✔ Container pgwatch3-postgres-1     Running                                         0.0s 
>  ✔ Container pgwatch3-add-test-db-1  Created                                         0.0s 
> Attaching to add-test-db-1
> Error response from daemon: network 5fd3cac23c91c89c3a2ae3743fb9ef5665a1bca5c3ff1b3a6e43b6cbd53fda16 not found
> Gracefully stopping... (press Ctrl+C again to force)
Since the container have been created and exited, it will reattach to the old container and fail. So we need to `force recreate` after `docker compose down` if we want to add test db again

[*] update docker compose command to force recreate test database

---

src/config/cmdoptions.go
src/main.go
src/metrics/postgres.go
src/metrics/yaml.go
src/metrics/yaml_test.go
src/sources/postgres.go

[*] make sources postgres reader follow the same pattern as YAML reader

[-] if presets are used then skip single metric checks, fixes #401

---

README.md
docker-compose.yml
docker/pgadmin_pass
docker/pgadmin_servers.json

- Add PGadmin into docker-compose.yml and README.md
- Change default login in Grafana to be admin, so you don't have to log in to change dashboards.
- Uncomments Prometheus section in docker compose file and adds profile so it can be started separately.
- Small changes in README.md like removing < > in pre tag, it was messing with how idea renders MD files.

[+] add pgAdmin4 to `docker-compose.yml`

---

src/config/cmdoptions.go
src/config/cmdoptions_test.go
src/main.go

[*] remove `--version` command option
[*] print help message for any error

[*] improve `--help` output

---

src/metrics/postgres_schema.go
src/reaper/reaper.go

Earlier we were returning the error along with the migrator. Fixed it to return error only when it occurs

[-] fix `dbMetricReaderWriter.initMigrator()` and init `reaper.metricDefinitioMap`

---

src/reaper/database.go
src/reaper/reaper.go
src/sources/postgres.go
src/sources/postgres_test.go
src/sources/resolver.go
src/sources/resolver_test.go
src/sources/types.go
src/sources/types_test.go
src/sources/yaml.go
src/sources/yaml_test.go
src/webserver/api.go
src/webserver/source.go

**Source** represents a configuration how to get databases to monitor. It can be a single database, a group of databases in postgres cluster, a group of databases in HA patroni cluster.
**MonitoredDatabase** represents a single database to monitor. Unlike source, it means a single physical database connection. Continuous discovery sources (postgres-continuous-discovery, patroni-continuous-discovery, patroni-namespace-discovery) will produce multiple monitored databases.
pgwatch first reads sources (single dbs, postgres and patroni clusters) and then lists all found databases in those as monitored databases

[!] differentiate the concepts of source and monitored database

---

src/reaper/cache.go
src/reaper/database.go
src/reaper/file.go
src/reaper/reaper.go
src/reaper/recommendations.go
src/reaper/types.go

`[*]` rename `DBVersionMapEntry` to `MonitoredDatabaseSettings` 
`[*]` rename `DBGetPGVersion()` to `GetMonitoredDatabaseSettings()` 
`[*]` refactor `GetMonitoredDatabaseSettings()`
`[*]` rename `MetricFetchMessage` to `MetricFetchConfig`

[-] fix metric version discovery for old PostgreSQL versions, fixes #489

---

src/reaper/database.go

Visual separation of integer using underscores was added in PG16
Fixes #494
Ran it in my lab environment where I have PG14 as source and no errors in log.

[-] fix version detection for pre-16 PostgreSQL, closes #494

---

internal/sources/resolver.go

[-] fix Patroni source resolving

---

internal/metrics/postgres_schema.sql

Remove hardcoded pgwatch user in config schema creation

---

internal/metrics/metrics.yaml

Add semi-colon to end of each statement so that concatenated SQL generated with "pgwatch metric print-init <preset>" is valid and can be piped to psql cli

[-] fix concatenated output of `pgwatch metric print-init`

---

internal/sources/types.go
internal/sources/yaml.go
internal/sources/yaml_test.go

Fixes issue #630 
(Hi, this is part of my preparation for GSoC 25)

[-] fix duplicate source names in YAML configs, fixes #630

---

internal/webui/src/hooks/useGridColumnVisibility.ts
internal/webui/src/pages/MetricsPage/components/MetricsGrid/MetricsGrid.tsx
internal/webui/src/pages/PresetsPage/components/PresetsGrid/PresetsGrid.tsx
internal/webui/src/pages/SourcesPage/components/SourcesGrid/SourcesGrid.tsx

- Ensures column visibility persists across refreshes.  
- Defaults to provided column settings if no saved state exists.  
- Implemented `useGridColumnVisibility` hook to manage column visibility state.  
- Saves visibility settings to `localStorage` to persist user preferences.  
- Restores saved settings on component mount.  
Closes #581

[+] persist visible column settings, fixes #581

---

grafana/postgres/v10/checkpointer-bgwriter-stats.json
grafana/postgres/v11/checkpointer-bgwriter-stats.json

- Adds support for PostgreSQL 17's pg_stat_checkpointer in the dashboard
- Modifies SQL query to union data from both bgwriter and checkpointer tables
- Maintains backward compatibility with pre-v17 PostgreSQL versions
closes #613

[-] fix checkpointer dashboards for PostgreSQL 17, fixes #613

---

docker/bootstrap/init_dbs.sh
docker/bootstrap/init_test_monitored_db.sh
docker/demo/Dockerfile
docker/demo/grafana.ini
docker/demo/supervisord.conf

`[+]` bump PostgreSQL to v17
`[*]` make Grafana use standard storage instead of Postgres
`[*]` use `full` preset for demo source instead of `exhaustive`
`[+]` use `pgwatch metric print-init` to prepare test monitoring source

[+] improve `pgwatch-demo` Docker image

---

internal/cmdopts/cmdsource.go
internal/metrics/logparse.go
internal/reaper/cache.go
internal/reaper/database.go
internal/reaper/reaper.go
internal/sources/conn.go
internal/sources/conn_test.go
internal/sources/postgres_test.go
internal/sources/resolver.go
internal/sources/types.go
internal/sources/types_test.go

Also move some connection specific functions from reaper to SourceConn methods, e.g. TryDiscoverExecutionEnv(), DoesFunctionExists()

[*] rename `sources.MonitoredDatabase` to `SourceConn`

---

docs/tutorial/custom_installation.md
docs/tutorial/upgrading.md

Some docs have `configurartion` instead of `configuration`.

[*] fix typo in documentation

---

grafana/postgres/v11/system-stats.json

- Removed a duplicate `"text": null` key in the `grafana/postgres/v11/system-stats.json` file under the `"current"` object.
->
- The duplicate key caused invalid JSON syntax, which could lead to parsing errors or unexpected behavior in Grafana dashboards.  
- JSON objects require unique keys; removing the duplicate ensures compliance with JSON standards.  
- Fixes syntax validity without altering functionality.  
- Improves reliability of the dashboard configuration.  
This is a straightforward syntax correction. No tests or additional documentation updates are required as the change does not affect logic or features.

[-] fix duplicate object key in `postgres/v11/system-stats.json`

---

docs/reference/advanced_features.md
grafana/postgres/v10/pgpool-stats.json
grafana/postgres/v11/pgpool-stats.json
internal/metrics/metrics.yaml
internal/metrics/types.go
internal/reaper/database.go
internal/reaper/reaper.go
internal/reaper/recommendations.go
internal/sources/conn.go
internal/sources/conn_test.go

- split `pgpool_stats` into two separate metrics
- update documentation
- update Grafana dashboards
- add `metrics.RowToMeasurement()`
- use `pgx.QueryExecModeSimpleProtocol` for non-Postgres connections
- remove `FetchMetricsPgpool()` and use standard fetching

[-] fix Pgpool-II support, closes #730

---

internal/reaper/database.go
internal/reaper/database_test.go
internal/reaper/version_test.go

- acquire connection from `SourceConn` instead of creating new
- use `md.Metrics` and `md.MetricsStandby`
- use common logger fields

[*] refactor `TryCreateMetricsFetchingHelpers`

---

go.mod
go.sum

introduced by Go 1.24.3 golang/go#73617

[-] fix duplicated definition of symbol `dlopen`

---

internal/reaper/cache.go
internal/reaper/reaper.go
internal/sources/conn.go
internal/sources/conn_test.go

* keep existing connection in `SourceConns.SyncFromReader()`
Since `SourceConn` passed to `reapMetricMeasurements()` it's crucial to keep the existing source with connection alive, so the reaper keeps it's work. And there is no need to close the connection because it might be used right now in some metric fetcher. Let Reaper to cancel all disabled monitored sources in the main loop of `Reap()` function.

[-] fix `QueryMeasurements` nil pointer dereference, fixes #766

---

internal/metrics/logparse.go
internal/reaper/database.go
internal/reaper/reaper.go
internal/sinks/json.go
internal/sinks/json_test.go
internal/sinks/multiwriter.go
internal/sinks/multiwriter_test.go
internal/sinks/postgres.go
internal/sinks/postgres_test.go
internal/sinks/prometheus.go
internal/sinks/rpc.go
internal/sinks/rpc_test.go

get rid of `[]metrics.MeasurementEnvelope` everywhere
Allocating additional slices increases a memory usage. Instead we can send `metrics.MeasurementEnvelope` one by one immediately after receiving. There is no need to collect them beforehand.
For 12 postgres instances monitored with full preset this change saves us ~4-9% of allocations.

[+] decrease memory allocations for `metrics.MeasurementEnvelope`

---

cmd/pgwatch/main.go
internal/reaper/cache.go
internal/reaper/database.go
internal/reaper/file.go
internal/reaper/metric_test.go
internal/reaper/reaper.go
internal/reaper/recommendations.go
internal/sources/conn.go
internal/sources/conn_test.go
internal/sources/resolver.go
internal/sources/types.go

Since reapers is responsible for connections and metric syncing it's better to move source synchronization to the reaper itself. Also get rid of `monitoredDbCache` and use `reaper.monitoredSources` directly. Now we can use `QueryMeasurements` directly with connection as an argument instead of the name to look in a cache.

[+] move sources sync to the reaper

---

internal/metrics/logparse.go
internal/metrics/logparse_test.go

Use `time.After()` instead of blocking `time.Sleep()`. Move preparation to the beginning of the function and do it only once. If configuration changes, reaper will destroy the current context and start another one with new configuration. No need to recalculate `csvlogRegex` and `logsGlobPath`. Add deferred latest handle closing. Add non-blocking send to sinks channel. Add unit tests.

[+] rewrite `ParseLogs()` with timers and eliminate extra checks

---

internal/reaper/database.go

This will decrease memory usage. Previously `QueryMeasurements()` returned a long slice of `map[string]any` creating pressure on heap.

[*] use `pgx.Rows` directly in `DetectConfigurationChanges()`

---

go.mod
go.sum
internal/db/conn.go
internal/reaper/reaper.go
internal/sinks/cmdopts.go
internal/sinks/json.go
internal/sinks/json_test.go
internal/sources/resolver.go
internal/webserver/jwt.go
internal/webserver/jwt_test.go
internal/webserver/metric.go
internal/webserver/metric_test.go
internal/webserver/server_test.go
internal/webserver/source.go
internal/webserver/source_test.go
internal/webserver/webserver_test.go

Replaced standard "encoding/json" with "github.com/json-iterator/go" to improve serialization/deserialization speed and reduce memory allocations.
This change is expected to lower CPU usage and heap pressure in high-throughput scenarios. Behavior remains compatible with the standard library.

[+] switch to `json-iterator/go` from `encoding/json`

---

internal/sinks/postgres.go
internal/sinks/prometheus.go

First make sure all sinks do not modify measurement envelopes, since maps in it reference to the same map in memory. Add improved Prometheus handler in sink, so logs will be populated with all scrapping errors. Clean cached measurements after each scrape, there is no need in serving the same data as it will be ignored anyway. Make sure all non-numeric fields are treated as labels. This will pollute some metrics, e.g. settings. It's better to rewrite metric queries if the number of labels is too high.

[-] improve Prometheus scrapping, fixes #749

---

internal/reaper/database.go
internal/reaper/reaper.go
internal/sinks/prometheus.go

Remove extra `setInstanceUpDownState()` from Prometheus sink. Add `reaper.GetInstanceUpMeasurement()` function and use it in `FetchMetric()`

[-] fix `instance_up` metric, closes #759

---

internal/log/log.go
internal/metrics/types.go
internal/reaper/reaper.go
internal/reaper/reaper_test.go
internal/sources/conn.go
internal/sources/conn_test.go
internal/sources/postgres_test.go

Rewrite `Reaper.LoadSources` to properly handle Groups. Drop `SourceConns.SyncFromReader()` as obsolete. Add `TestReaper_LoadSources` tests.

[-] fix `--group` command-line option, closes #792

---

internal/reaper/reaper.go

move the `hostLastKnownStatusInRecovery[monitoredSource.Name] = monitoredSource.IsInRecovery` update to after the processing of the last cached value
closes: #814

[*] fix `Reap()` method to update Recovery cache after processing the previous value

---

grafana/postgres/v12/biggest-relations.json
grafana/postgres/v12/change-events.json
grafana/postgres/v12/checkpointer-bgwriter-stats.json
grafana/postgres/v12/global-health.json
grafana/postgres/v12/health-check.json
grafana/postgres/v12/index-overview.json
grafana/postgres/v12/pgbouncer-stats.json
grafana/postgres/v12/pgpool-stats.json
grafana/postgres/v12/postgres-version-overview.json
grafana/postgres/v12/recommendations.json
grafana/postgres/v12/replication.json
grafana/postgres/v12/server-log-events.json
grafana/postgres/v12/sessions-overview.json
grafana/postgres/v12/show-plans-realtime.json
grafana/postgres/v12/single-query-details.json
grafana/postgres/v12/sproc-details.json
grafana/postgres/v12/sprocs-top.json
grafana/postgres/v12/stat-activity-realtime.json
grafana/postgres/v12/stat-activity.json
grafana/postgres/v12/stat-statements-sql-search.json
grafana/postgres/v12/stat-statements-top-fast.json
grafana/postgres/v12/stat-statements-top-visual.json
grafana/postgres/v12/stat-statements-top.json
grafana/postgres/v12/system-stats-time-lag.json
grafana/postgres/v12/system-stats.json
grafana/postgres/v12/table-details-time-lag.json
grafana/postgres/v12/table-details.json
grafana/postgres/v12/tables-top.json

In first phase of this PR , following files were updated ( 14 files )
biggest-relations.json
change-events.json
checkpointer-bgwriter-stats.json
index-overview.json
sproc-details.json
sprocs-top.json
stat-activity-realtime.json
stat-activity.json
stat-statements-top-visual.json
stat-statements-top.json
system-stats-time-lag.json
system-stats.json
table-details-time-lag.json
tablestop.json
IN PHASE 2 OF THIS PR, following files were updated ( 14 files )
global-health.json
health-check.json
pgbouncer-stats.json
pgpool-stats.json
postgres-version-overview.json
recommendations.json
replication.json
server-log-events.json
sessions-overview.json
show-plans-realtime.json
single-query-details.json
stat-statements-sql-search.json
stat-statements-top-fast.json
table-details.json
14 files + 14 files …

updating grafana postgres dashboards to v-12

---

internal/sources/types.go
internal/sources/types_test.go

ensure `SourceConn.Equal()` doesn't mark sources with empty presets as equal directly.
closes: #830

[-] fix `Source.Equal()` presets comparison, closes #830

---

internal/sources/types.go
internal/webserver/metric.go
internal/webserver/metric_test.go
internal/webserver/source.go
internal/webserver/source_test.go
internal/webserver/webserver.go

- Add `/[source|metric|preset]/{name}` routes using Go 1.22+ PathValue
- Implement GET, PUT, DELETE methods with proper HTTP status codes
- Add comprehensive test coverage for new REST endpoints
- Maintain backward compatibility with existing collection endpoints
- Use idempotent PUT/DELETE semantics

[!] add REST-compliant endpoints with path parameters

---

docker/compose.grafana.yml
grafana/postgres/v11/stat-statements-sql-search.json
grafana/postgres/v11/stat-statements-top-visual.json
grafana/postgres/v11/stat-statements-top.json

- Replace deprecated Angular panels with built-in table panels in `grafana/postgres/v11` `stat-statements` dashboards.

[*] improve stat-statements Grafana v11 Postgres dashboards

---

internal/sources/postgres.go

Remove `host_config` querying from `GetSources()`.
The reaper fails to read sources from postgres due to `pgx.CollectRows[Source]` in `GetSources()` giving error about missing `host_config` field from `Source` Struct
```
go run ./cmd/pgwatch --sources=postgres://postgres:postgres@localhost:5432/postgres --sink=jsonfile://file.json
2025-07-24 22:21:47.569 [ERROR] [error:struct doesn't have corresponding row field host_config] could not refresh active sources, using last valid cache
2025-07-24 22:21:47.571 [INFO] [metrics:73] [presets:17] metrics and presets refreshed
```
`host_config` field was removed from source in #859

[-] remove `host_config` querying from `GetSources()`

---

internal/sinks/rpc.go
internal/sinks/rpc_test.go

- send `username` and `password` contained in the grpc sink uri  `grpc://username:password@...` with each call's metadata to enable authentication for servers

[+] add basic auth support to grpc sink

---

.dockerignore
.github/actions/build-docker/README.md
.github/actions/build-docker/action.yml
.github/workflows/build.yml
.github/workflows/docker-build.yml
.github/workflows/docker.yml
.github/workflows/release.yml
docker/Dockerfile
docker/demo/Dockerfile

- use official Docker actions (`docker/build-push-action@v5`, `docker/metadata-action@v5`, etc.)
- automatic SemVer tagging with `docker/metadata-action`
- test builds without registry authentication
- add custom Docker Manual Multi-Registry Build action and reuse it

[!] improve Docker-related GitHub Actions and jobs

---

internal/sources/postgres.go

- Change number of sql query parameters in `updateSources()` to be `13` not `14` 
---
After removing `host_config` from sources in #859 `updateSources()` sql query should take `13` parameters not `14`. 
currently any sources update gives the following error:
```
[err:ERROR: INSERT has more expressions than target columns (SQLSTATE 42601)] [pid:39828] [time:686.266µs] Query
```

[*] fix `updateSources()` query parameters number

---

internal/metrics/yaml.go
internal/metrics/yaml_test.go
internal/sources/resolver_test.go
internal/sources/yaml.go

add `loadMetricsFromYaml()` to load metrics from file or folder of yaml files
- read single yaml file or all yaml files in folder, unmarshal it/them, then copy it/them to the global `metrics.MetricDefs` and `metrics.PresetDefs` maps 
---
another PR that builds on top of this to make `Create[Metric|Preset]()`, `Update[Metric|Preset]()`, `Delete[Metric|Preset]()` functions handle metrics folder will be provided.        
closes: #882

[+] allow metrics loading from folder, closes #882

---

docs/gallery/webui.md
docs/reference/cli_env.md
docs/reference/env_variables.md
internal/cmdopts/cmdsource.go
internal/webserver/cmdopts.go

- fix typo in `webui.md` doc
- mention `Cli & Envs` section instead of `pgwatch -h` in `env_variables.md`
- move `create-helpers` under sources section not metrics

[*] misc minor updates to docs

---

docs/concept/installation_options.md
docs/reference/rest.md

- add note in docs about yaml folder based configs being read-only
- mention using yaml-folder for metrics configs in docs

[*] update docs for metrics yaml folder configs

---

internal/reaper/reaper.go

If some source is not available for resolving then it blocks all other sources. So just log the error and proceed with sources available at the moment. Re-sync on the next iteration.

[-] do not fail on db resolve error, just log an error, fixes #890

---

contrib/sample.metrics.yaml
docker/compose.pgwatch.yml
docker/compose.postgres.yml
docs/reference/metric_definitions.md
grafana/postgres/v12/recommendations.json
internal/metrics/metrics.yaml

Refactor PostgreSQL recommendation metrics to consolidate multiple
findings per metric type.
The changes consolidate all 8 recommendation metrics to use
an aggregation pattern that combines multiple database objects into
comma-separated strings instead of separate rows, limiting results to
50 items with overflow indicators, and actionable guidance templates
were added to extra_info fields.

[+] improve recommendation metrics,  #764

---

internal/reaper/database.go
internal/reaper/database_test.go
internal/reaper/metric.go
internal/reaper/reaper.go
internal/sources/conn.go

Move `HostState` to `RuntimeInfo.ChangeState` for better data organization.
Convert standalone detection functions to `Reaper` methods for consistency. Replace verbose `Info` logs with structured `Debug` logs using `WithField()`.
Eliminate `hostState` parameter passing throughout detection methods.
Add `Total()` and `String()` helper methods to `ChangeDetectionResults`.
Improve change summary with structured logging fields instead of string concatenation. Simplify deletion tracking by removing intermediate arrays

[+] improve `change_events` metric processing
